### ISSUE TITLE
Compilation error when building rust-app

### ISSUE THREAD

**Issue by mkschreder** [tylerwhall/zephyr-rust#31]
![image](https://user-images.githubusercontent.com/4483721/191919511-603b55d9-9780-4205-96a4-8645405ecaf3.png)

Seems to be simply outdated code. On zephyr 3.1 should be STRUCT_SECTION_ITERABLE without the Z prefix

**Comment by tylerwhall** [comment]
Yeah, I've only tested up to 2.5 and I personally need to maintain support for 2.3 for my company. So I haven't had the need yet to port to newer Zephyr. Would accept patches.
