### ISSUE TITLE
Rust analyzer

### ISSUE THREAD

**Issue by hkjolhede** [tylerwhall/zephyr-rust#39]
Have you had any luck using rust analyzer in VSCode with zephyr-rust? As far as I can tell it would require adding a "check"-equivalent command to the west workspace. Do you have any experience with that?

**Comment by tylerwhall** [comment]
I haven't attempted it, so I don't have any immediate advise. The main project I use this with has the application as a separate crate that builds and runs under Linux as well as Zephyr, so I'm able to do develop it as a normal Rust project outside of Zephyr.

**Comment by tylerwhall** [comment]
@hkjolhede if you come up with a setup for making it work, we can add it here.
